version: "3.8"
services:
  reverse-proxy:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.app.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  app:
    build:
      context: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=app"
    volumes:
      - ./app/src:/var/www/app
    depends_on:
      - reverse-proxy
      - mongodb
